development:
  adapter: postgresql
  encoding: unicode
  database: eurodom_development
  pool: 5
  timeout: 5000
  username: onlyreflex
  password: aeoeawsiohgou3213ik1qr5
test:
  adapter: postgresql
  encoding: unicode
  database: eurodom_test
  pool: 5
  timeout: 5000
  username: onlyreflex
  password: aeoeawsiohgou3213ik1qr5
